author = "Willem Vanhulle"
base_url = "https://willemvanhulle.be"
title = "Willem Vanhulle"


build_search_index = true
compile_sass = true
feed_filenames = ["atom.xml"]
generate_feeds = true
taxonomies = [{ name = "tags", description = "Tags" }]

[markdown]

# Navigation
bottom_footnotes = true

# Prose
render_emoji = true
smart_punctuation = true

# # Code
# highlight_code = true
# highlight_theme = "demain"
# error_on_missing_highlight = true
